//
//  InfoPageView.swift
//  OLMoE.swift
//
//  Created by Thomas Jones on 11/13/24.
//

import SwiftUI

struct InfoPageData {
    let title: String
    let text: String
    let buttonText: String
}

// Placeholder disclaimer text displayed at app start
let infoPages = [
    
    InfoPageData(title: "[TODO] Disclaimers",
             text: "[TODO] - Some legal text disclaimer here. The next page will be the 'Limitations' disclaimer from the Playground...",
             buttonText: "OK"),
    
    InfoPageData(title: "Limitations",
             text: "Large pretrained language models, such as OLMo and Tulu, are trained on mostly unfiltered internet data, and therefore are extremely quick to produce toxic, unethical, and harmful content, especially about minority groups. Ai2 uses several strategies to mitigate these behaviors for the benefit of the general public, but please note model outputs will still contain biases, toxic content, or harmful language. These undesirable results have a legitimate research purpose, however, especially for researchers investigating the sources of bias, toxicity, and harmful language generated by...",
             buttonText: "I Agree")
]

struct InfoPage: View {
    typealias PageButton = (text: String, onDismiss: () -> Void)
    
    let title: String
    let message: String
    let confirm: PageButton
    
    var body: some View {
        VStack(spacing: 20) {
            
            Text(title)
                .font(.headline)
                .padding(.top, 20)
            
            Text(message)
                .font(.body)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 20)
            
            Button(confirm.text) {
                confirm.onDismiss()
            }
            .padding(.bottom, 20)
        }
    }
}
